### ISSUE TITLE
I have problem using trying out the first example?

### ISSUE THREAD

**Issue by scaruslooner** [datavorous/yars#12]
Z:\AI\yars (reddit scraper)\yars>poetry shell
The currently activated Python version 3.10.11 is not supported by the project (^3.12).
Trying to find and use a compatible version.
Using python3.12 (3.12.3)
Creating virtualenv yars-7S-mp-Ci-py3.12 in C:\Users\camer\AppData\Local\pypoetry\Cache\virtualenvs
Spawning shell within C:\Users\camer\AppData\Local\pypoetry\Cache\virtualenvs\yars-7S-mp-Ci-py3.12

(yars-py3.12) Z:\AI\yars (reddit scraper)\yars>poetry install
Installing dependencies from lock file

Package operations: 7 installs, 0 updates, 0 removals

  - Installing certifi (2024.8.30)
  - Installing charset-normalizer (3.3.2)
  - Installing idna (3.10)
  - Installing urllib3 (2.2.3)
  - Installing logging (0.4.9.6)
  - Installing pygments (2.18.0)
  - Installing requests (2.32.3)

Installing the current project: yars (0.1.0)
Warning: The current project could not be installed: [Errno 2] No such file or directory: 'Z:\\AI\\yars (reddit scraper)\\yars\\README.md'
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!

(yars-py3.12) Z:\AI\yars (reddit scraper)\yars>poetry run python ".\tests\example1.py"
Traceback (most recent call last):
  File "Z:\AI\yars (reddit scraper)\yars\tests\example1.py", line 1, in <module>
    from yars.yars import YARS
ModuleNotFoundError: No module named 'yars'

(yars-py3.12) Z:\AI\yars (reddit scraper)\yars>cd yars

(yars-py3.12) Z:\AI\yars (reddit scraper)\yars\yars>poetry run python example1.py
C:\Python312\python.exe: can't open file 'Z:\\AI\\yars (reddit scraper)\\yars\\yars\\example1.py': [Errno 2] No such file or directory

(yars-py3.12) Z:\AI\yars (reddit scraper)\yars\yars>poetry run python example1.py
Traceback (most recent call last):
  File "Z:\AI\yars (reddit scraper)\yars\yars\example1.py", line 1, in <module>
    from yars.yars import YARS
  File "Z:\AI\yars (reddit scraper)\yars\yars\yars.py", line 6
    from __future__ import annotations
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file

(yars-py3.12) Z:\AI\yars (reddit scraper)\yars\yars>

**Comment by SpreadSheets600** [comment]
@scaruslooner hello there, 
You need python 3.12 for this project please upgrade your python version

**Comment by datavorous** [comment]
@scaruslooner You should upgrade to python 3.13 and use ```uv``` . Please check out the recent changes to our main branch.
