### ISSUE TITLE
Set a random User Agent with each request

### ISSUE THREAD

**Issue by hammadbinsajjad** [datavorous/yars#15]
Viewing the recently merged pull request #7, i thought that this functionality can be extended to set a new user agent to every subsequent request instead of just setting it one time when the miner (class YARS) object is made. This might help prevent being blocked from the server even more. Following are the details of my approach to implement this.

1. Create a custom session class by inheriting from the requests.Session class.
2. Override the get function and update the User Agent in the current session headers by getting a random one.
3. Call the parent class' get function and (if required) pass the new updated headers as parameter to it.
4. Use this class instead of the requests.Session class in the yars.py file.

Let me know if you think this approach can benefit this package, I can then start implementing this and will create a pull request with the changes.

**Comment by datavorous** [comment]
@hammadbinsajjad I've assigned you with this issue. Please use ```uv``` for dependency management.

**Comment by hammadbinsajjad** [comment]
Thank you. Will start working on the implementation today and make a PR once I am done with it.
